steps:
  - name: "gcr.io/cloud-builders/mvn"
    args:
    - package


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tomas:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/tomas:latest', '-f', 'Dockerfile2',  '.' ]  
    
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nginx:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/nginx:latest',  '.' ]
    
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'set', 'image', 'deployment/nginx-deployment', 'nginx=gcr.io/$PROJECT_ID/nginx:$TAG_NAME', '--record' ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-epam'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'set', 'image', 'deployment/tomcat-deployment', 'tomcat=gcr.io/$PROJECT_ID/tomas:$TAG_NAME', '--record' ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-epam'
 

images:
- 'gcr.io/$PROJECT_ID/tomas'   
- 'gcr.io/$PROJECT_ID/nginx'
