steps:
  #- name: "gcr.io/cloud-builders/mvn"
 #   args:
#    - package

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo $$VAULT_T']
    secretEnv: ['VAULT_T']
  
  - name: 'gcr.io/epam-267215/curljq'
    args: ['curl', '-o', '/workspace/txt', '-v', '-k', '-H', 'X-Vault-Token: $$VAULT_T', $PRIV_T]
    secretEnv: ['VAULT_T','PRIV_T']

  - name: 'gcr.io/epam-267215/curljq'
    args: ['curl', '-o', '/workspace/ful', '-v', '-k', '-H', 'X-Vault-Token: $$VAULT_T', '$$FULL_T']
    secretEnv: ['VAULT_T','FULL_T']
 

  - name: 'gcr.io/epam-267215/curljq'
    args: ['cat', '/workspace/txt' ]

  - name: 'gcr.io/epam-267215/curljq'
    entrypoint: /bin/bash
    args: ['-c', 'jq -r .data.data.value /workspace/txt > /workspace/privkey.pem' ]


#  - name: 'gcr.io/epam-267215/curljq'
#    args: ['jq', '-r', '.data.data.value', '/workspace/txt', '>', '/workspace/privkey.pem' ]

  - name: 'gcr.io/epam-267215/curljq'
    args: ['cat', '/workspace/txt' ]

  - name: 'gcr.io/epam-267215/curljq'
    args: ['cat', '/workspace/privkey.pem' ]



  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tomas:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/tomas:latest', '-f', 'Dockerfile2',  '.' ]  
    
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nginx:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/nginx:latest',  '.' ]
    
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'set', 'image', 'deployment/nginx-deployment', 'nginx=gcr.io/$PROJECT_ID/nginx:$TAG_NAME', '--record' ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-epam'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'set', 'image', 'deployment/tomcat-deployment', 'tomcat=gcr.io/$PROJECT_ID/tomas:$TAG_NAME', '--record' ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-epam'
 

images:
- 'gcr.io/$PROJECT_ID/tomas'   
- 'gcr.io/$PROJECT_ID/nginx'
secrets:
- kmsKeyName: projects/epam-267215/locations/europe-north1/keyRings/google-keys/cryptoKeys/vault-token
  secretEnv:
    VAULT_T: CiQARyYZPDWUioF9jAX/K72QgHMP9a9fHSa107cfxWPNJov1EmISRAAZHrxOeeQD6a55630k3BUDsP+aBcBIMBOcu2NrLhK9zZkMIznGGfaYAk+KwFD4u2pYjftLlWjBtU5E0+s3WJTyM5TG
    PRIV_T: CiQARyYZPOJWVuJLcYAKZuhvnugV2DDailPUPhIohand9KKHT8QSWQAZHrxO9TIaWVPJdtMC/Yhf6mWTWbXYBoRuqyEJYIKR921Fbz3yFr6Dctb07+gv6L9eZ6wVpJi4ZIQKdR8q9iMfE7VxIMXpVoPaa+ZEmlMzO7SWxGuhNVyE
    FULL_T: CiQARyYZPNaLbXfraiECU7Pn2JQglPr/tTeQ8VO//bLOgTaiGu8SXAAZHrxOKX2AMTeG2wKHHBcn4qtey3gPxuIR0BdSyLDStPy8Ofm87xs7sNwfYRo+CMTPMAyfhnlibvTRfjnECJjjMJ2W3N86JO5fuu0JKjEYSM/ROO0vVgyEku3P

